# conda env create -f environment.yml
name: fel2024
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - bmad
  - pytao
  - genesis4 >=4.6.6=mpi_openmpi*
  - lume-genesis
  - pytest
  - zfel
  - jupyterlab>=3
  - jupyterlab-lsp
  - python-lsp-server

